[package]
name = "scrum_poker"
version = "0.1.0"
authors = ["marko.lazic <markolazic@protonmail.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1.35.0", features = ["full", "tracing"] }
futures = "0.3.29"
axum = { version = "0.6.20", features = ["tokio", "ws"] }
axum_session = { version = "0.9.0", features = ["surrealdb-mem"] }
dioxus = "0.4.3"
dioxus-liveview = { version = "0.4.3", features = ["axum"] }
fermi = "0.4.3"
surrealdb = { version = "1.0.2", features = ["kv-mem"] }
deadpool = "0.10.0"
serde = { version = "1.0.193", features = ["serde_derive"] }
tower-http = { version = "0.4.0", features = ["fs"] }
thiserror = "1.0.52"
uuid = "1.6.1"

[profile.dev]
opt-level = 1


[profile.dev.package."*"]
opt-level = 3
