[package]
name = "scrum_poker"
version = "0.1.0"
authors = ["marko.lazic <markolazic@protonmail.com>"]
edition = "2021"

[dependencies]
axum = { version = "0.6.20", features = ["tokio", "ws"] }
dioxus = "0.4.3"
dioxus-liveview = { version = "0.4.3", features = ["axum"] }
tokio = { version = "1.35.0", features = ["full"] }
tower-http = { version = "0.4.0", features = ["fs"] }


[profile.dev]
opt-level = 1


[profile.dev.package."*"]
opt-level = 3
