[workspace]
resolver = "2"
members = [
    "web",
    "services/*",
]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
