# fly.toml app configuration file generated for scrumpokerdb on 2024-02-23T22:41:08+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scrumpokerdb'
primary_region = 'otp'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'

[mounts]
source = "data"
destination = "/data"
